# NumPy 

Numerical Python or simply NumPy is a Linear Algebra Library for Python.

Here's a wonderful post of why you should use NumPy Arrays instead of lists: [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

## Using NumPy

Import NumPy as a library:

In [2]:
import numpy as np

NumPy has many built-in functions and capabilities. Some of the most important aspects of NumPy include: vectors, arrays, matrices, and number generation.

# NumPy Arrays

NumPy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1D arrays and matrices are 2D (however, matrix may have only one row or one column).


## Creating NumPy Arrays

### From a Python List

In [36]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [37]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are a lot of built-in ways to generate NumPy Arrays

### arange

Return evenly spaced values within a given interval.

In [7]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [9]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [10]:
np.zeros((5, 5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [11]:
np.ones(3)

array([ 1.,  1.,  1.])

In [12]:
np.ones((3, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [13]:
np.linspace(0, 10, 3)

array([  0.,   5.,  10.])

In [14]:
np.linspace(0, 10, 50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

## eye

Creates an identity matrix

In [15]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## Random 

NumPy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [16]:
np.random.rand(2)

array([ 0.39365358,  0.4925529 ])

In [17]:
np.random.rand(5, 5)

array([[ 0.08225739,  0.28408698,  0.77793868,  0.70879457,  0.74805826],
       [ 0.77866644,  0.90435225,  0.09791826,  0.41430382,  0.75516617],
       [ 0.78448898,  0.63949302,  0.06425943,  0.21291921,  0.88745293],
       [ 0.22382355,  0.18844915,  0.0453665 ,  0.55256507,  0.04030589],
       [ 0.32834767,  0.29188542,  0.06565127,  0.84516623,  0.44550669]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [18]:
np.random.randn(2)

array([-0.88370379, -0.8452441 ])

In [19]:
np.random.randn(5, 5)

array([[-1.08315727,  1.99806561,  0.4016882 , -2.10511901,  0.065978  ],
       [ 1.0371245 ,  0.13866705,  0.59474806,  0.44257131,  0.9472808 ],
       [ 1.60071616, -0.57924504,  0.13556638, -0.18665121,  0.5879115 ],
       [-0.80105041,  0.97973139, -1.55641073, -0.20756453,  1.00474337],
       [-1.22957133,  0.31976653, -0.35979243, -0.13041761, -0.36277129]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [20]:
np.random.randint(1, 100)

31

In [21]:
np.random.randint(1, 100, 10)

array([37, 82, 25, 77, 60,  9, 35,  5, 24, 56])

## Array Attributes and Methods

Here are some useful attributes and methods of an array:

In [22]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
ranarr

array([13, 29, 41, 15, 42, 26, 22, 41,  6,  0])

## Reshape
Returns an array containing the same data with a new shape.

In [25]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max, min, argmax, argmin

These are useful methods for finding max or min values. To find their index locations use argmin or argmax.

In [26]:
ranarr

array([13, 29, 41, 15, 42, 26, 22, 41,  6,  0])

In [27]:
ranarr.max()

42

In [28]:
ranarr.argmax()

4

In [29]:
ranarr.min()

0

In [30]:
ranarr.argmin()

9

## Shape

Shape is an attribute that arrays have:

In [31]:
# Vector
arr.shape

(25,)

In [32]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [33]:
arr.reshape(1,25).shape

(1, 25)

In [34]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [38]:
arr.reshape(25, 1).shape

(25, 1)

### dtype

To find the data type of the object in the array:

In [36]:
arr.dtype

dtype('int32')